# mcp-server/docker-compose.yml
services:
  redis:
    image: redis/redis-stack-server:7.2.0-v9   # same as before
    ports: ["6379:6379"]

  grafana:
    image: grafana/grafana-oss:10.4.4
    ports: ["3001:3000"]
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      # Remove the subpath settings
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - redis
  web:
    image: ghcr.io/ericmariasis/ai-web:latest
    env_file:
      - .env.docker
    expose: ["3000"]
    depends_on:
      - server

  nginx:
    image: nginx:1.27-alpine
    ports: 
      - "80:80"           # Production port mapping
      - "443:443"         # HTTPS port for SSL
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl.conf:/etc/nginx/conf.d/ssl.conf:ro
      - ./nginx/common-routes.inc:/etc/nginx/conf.d/common-routes.inc:ro
      # Mount Let's Encrypt certificates (uncomment when ready for production SSL)
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web
      - grafana
  server:                       # 👈 new
    build:
      context: .
      dockerfile: Dockerfile    # see below
    env_file:
      - .env.docker
    environment:
      - REDIS_URL=redis://redis:6379
      - PORT=4000               # whatever your server listens on
    ports:
      - "4000:4000"
    depends_on:
      - redis

volumes:
  grafana-data:
