name: Crawl + Prune Algolia

on:
  push:
    branches: [main]         # every commit on main
  schedule:
    - cron:  '15 4 * * *'    # nightly 04:15 UTC
  workflow_dispatch:         # manual “Run workflow” button

jobs:
  prune:
    runs-on: ubuntu-latest

    # Make every step start in mcp-server/ by default ↓↓↓
    defaults:
      run:
        working-directory: mcp-server

    env:
      ALGOLIA_APP_ID:  ${{ secrets.ALGOLIA_APP_ID }}
      ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node 20 + restore npm cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          # point cache at the *right* lock‑file
          cache-dependency-path: mcp-server/package-lock.json

      - name: Install dependencies (npm ci)
        run: npm ci

      - name: Prune to newest 1 000
        run: npx ts-node src/scripts/prune_latest.ts 1000
