name: Crawl + Prune Algolia

on:
  push:              # every push to main
    branches: [ main ]
  schedule:          # every night at 04:15 UTC
    - cron:  '15 4 * * *'
  workflow_dispatch: # manual Run workflow button

jobs:
  prune:
    runs-on: ubuntu-latest

    env:            # available to **all** steps
      ALGOLIA_APP_ID:  ${{ secrets.ALGOLIA_APP_ID }}
      ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Node & deps
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci            # install from package‑lock

      # ---------- YOUR SCRIPT ---------------
      - name: Prune to newest 1000
        run: npx ts-node mcp-server/scripts/prune_latest.ts 1000